### ISSUE TITLE
Crash on Plugin load with Paper 1.16.5-571

### ISSUE THREAD

**Issue by MrAusnadian** [vinhowe/Hound#6]
```
[18:51:16 INFO]: [Hound] Enabling Hound v0.3.0
[18:51:16 ERROR]: Error occurred while enabling Hound v0.3.0 (Is it up to date?)java.lang.NoClassDefFoundError: kotlin/collections/CollectionsKt
        at ChestSearchCommand.<clinit>(ChestSearchCommand.kt:153) ~[?:?]
        at Hound.onEnable(Hound.kt:43) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[patched_1.16.5.jar:git-Paper-571]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:380) ~[patched_1.16.5.jar:git-Paper-571]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:483) ~[patched_1.16.5.jar:git-Paper-571]
        at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugin(CraftServer.java:501) ~[patched_1.16.5.jar:git-Paper-571]
        at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugins(CraftServer.java:415) ~[patched_1.16.5.jar:git-Paper-571]
        at net.minecraft.server.v1_16_R3.MinecraftServer.loadWorld(MinecraftServer.java:580) ~[patched_1.16.5.jar:git-Paper-571]
        at net.minecraft.server.v1_16_R3.DedicatedServer.init(DedicatedServer.java:280) ~[patched_1.16.5.jar:git-Paper-571]
        at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1055) ~[patched_1.16.5.jar:git-Paper-571]
        at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:289) ~[patched_1.16.5.jar:git-Paper-571]
        at java.lang.Thread.run(Thread.java:832) [?:?]
Caused by: java.lang.ClassNotFoundException: kotlin.collections.CollectionsKt
        at java.net.URLClassLoader.findClass(URLClassLoader.java:435) ~[?:?]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:182) ~[patched_1.16.5.jar:git-Paper-571]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:111) ~[patched_1.16.5.jar:git-Paper-571]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:589) ~[?:?]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:522) ~[?:?]
        ... 12 more
[18:51:16 INFO]: [Hound] Disabling Hound v0.3.0
```

**Comment by vinhowe** [comment]
You need to extract the appropriate Kotlin libraries into the jar when
building it. I use IntelliJ's Build Artifacts function, which makes that
pretty easy. It may be that I need to change the build.gradle.

**Comment by MrAusnadian** [comment]
> You need to extract the appropriate Kotlin libraries into the jar when
building it.

I'm not sure how to do that. I was just doing this:
```
1. Save `BuildTools.jar` to `C:\BuildTools`
2. Open PowerShell, change directory to `C:\BuildTools` (`cd C:\BuildTools`)
3. Run `java -Xmx1024M -jar BuildTools.jar --rev 1.16.5` and wait about 15 minutes
3. Open PowerShell and change directory to C: (`cd C:`)
4. Run `git clone https://github.com/vinhowe/Hound.git`
5. Change to Hound directory (`cd Hound`)
6. Run `.\gradlew.bat build`
7. Copy `Hound-0.3.0.jar` from `C:\Hound\build\libs` into my servers `plugins` folder
```

**Comment by vinhowe** [comment]
@MrAusnadian are you able to build as of https://github.com/vinhowe/Hound/commit/a1ca5042e2f0b2c2c94282b0ca4c511bf445a4c8?
